### ISSUE TITLE
How to skip validation of nested form?

### ISSUE THREAD

**Issue by jumski** [trailblazer/reform#315]
I have a simple form, like this:

``` ruby
class CopyForm < Reform::Form
  property :condition
  property :purchase_price
  property :edition_id

  property :edition, form: EditionForm, skip_if: ->(*) { edition_id.present? }
end
```

I want to validate `EditionForm` only if `:edition_id` is blank. How can i accomplish this? Tried with `skip_if` as above but it does not yield expected results.

Thanks in advance
Wojtek

**Comment by apotonick** [comment]
Hey Wojtek, this will be possible in Reform 2.1 or 2.2, where you will have validation groups that can be chained and can be suppress/run depending on outcomes of other group evaluations.

**Comment by apotonick** [comment]
BTW, if

**Comment by jumski** [comment]
does it need to be so complicated? is it because populating a form is only done via validate?

i wanted to hack a simple `skip_validation_if` option for subforms and filter out schema in  `lib/reform/contract/validate.rb`'s `validate_nested!` to filter out subforms we do not want to validate, but then i need to still show their content somehow, and setting values is only done via `validate` (which i do not want to call :))

will those groups support arbitrary conditions (proc or method symbol), or are only mean to rely on other groups validation status? already saw `validation-groups` branch but it is little work done there and hard to judge yet

thanks in advance

**Comment by apotonick** [comment]
You could also override `#validate` in the respective nested form(s) and apply your logic there?

**Comment by Haar** [comment]
Do we have any details on how to do this in 2.1+? Trying to do something similar myself.

**Comment by jumski** [comment]
No clue, i implemented it using `Virtus` and some glue code to instantiate/populate nested forms - works like a charm :)

**Comment by apotonick** [comment]
It could probably be implemented using the `:if` for validation groups, which is part of 2.1.

I'm getting a bit tired of the "Reform is so complicated, I rewrote it with Virtus and my own hacks" argument. Gems bring standards and try to solve a bunch of problems with as minimal code as possible for a huge community.

**Comment by jumski** [comment]
What's wrong in scrathing your own itches the way you value the most?
I've invested several hours into making reform work with my particular form, even hacked on my own fork, but all that coding has lead me to working around reform desing, which in coclusion lead me to just using Virtus.

One thing i had problem with is that the only way to populate a subform with values (which i need to render them on the page) is to validate it, which leads to my main form being invalid.

The second thing is, in my opinion validation groups was a wrong way to solve the conditional validation problem (maybe it was an effect of enforcing form validation if you want to populate it? do not remember the reform internals). IMO it is unnecessary abstraction over a simple problem of using a lambda to decide if validation should be run or not. With a simple `:if` option that accepts same objects as callbacks in rails (and other libs) you get:

* large audience that is familiar with the solution
* a building block for implementing the mentioned groups (if needed).

Hope this is more substantial argument that my previous one.

Cheers

**Comment by apotonick** [comment]
Everything is a "simple problem" when you're only talking about "your own" problems - once you start solving problems for a huge user base, it gets a bit more complicated and you have to pick your API wisely. This in turn is, very often, in our generous OSS community, interpreted as "too complicated".

TBH, I still don't understand what your request involves. You want to populate the nested form with the input (from `validate`) and then only run validations for nested forms if your `:if` is evaluated to true? Is that what you mean by "to decide if validation should be run or not"?

**Comment by jumski** [comment]
sure, i am only an api consumer and reform api deviates from well defined (but not formalized) standards, hence my confusion

for you understanding - you are correct. the reasoning tl;dr; is that i want to either use related model (so fkey is filled), or create a new one, but use some fields from the existing one, not worth more explanation because it is already solved and was just a refactoring

cheers

**Comment by apotonick** [comment]
Haha, ok! Can I still ask you some more? :beers: 

So, to me it sounds more like a *population* problem, not a *validation* problem. When calling `form.validate(..)`, this is a two-steps workflow.

1. The incoming params is deserialized into the nested form. That's called *population*.
2. This graph is then validated, and obviously, this step is named *validation*. 

It feels as if you could've achieved that with a `:populator`, which is a lambda that allows arbitrary population code, and then use `skip!` to omit the remaining workflow. http://trailblazer.to/gems/reform/populator.html#skip

I am guessing that additionally, after the tree is set up whatever way, you also wanted to skip validation for existing models?

**Comment by Haar** [comment]
The current use-case that I have a Form has properties, (e.g. amount), and if you select a model then it validates the amount meets that models minimum_amount. There are several validations that should take place only if the model is selected, e.g.:

``` ruby

class MyForm

  property :amount, type: Decimal
  validates :amount, presence: true, numericality: { greater_than: 0 }

  property :model_id

  # if model selected
    validates :amount, numericality: {greater_than: -> {model.minimum_amount}}, if: -> (_) { model.minimum_amount.present } # Not all instances of Model have a minimum amount
    # other validations
  # endif

  def model
    @model ||= Model.find_by(id: model_id)
  end
end
```

At this point would it be better just writing custom validation methods to be run?

**Comment by apotonick** [comment]
I think this is a perfect candidate for @solnic and the dry-validation gem that we integrated into Reform. Piotr, how would you write that in dry-v (pseudo-code, please)?

**Comment by solnic** [comment]
@apotonick I...don't know how this could be done in Reform+dry-v :) With a plain schema it'd be sth like that:

``` ruby
ModelSchema = Dry::Validation.Schema(build: false) do
  configure do
    option :model

    def min_amount?(amount)
      model.minimum_amount.nil? || amount > model.minimum_amount
    end

    key(:amount).maybe(:int?, :min_amount?)
  end
end

schema = ModelSchema.with(model: Model.find_by(id: model_id)
schema.(amount: 1)
```

**Comment by AnwarShah** [comment]
How do I avoid processing of a fragment (I don't know if it is the current term) or nested hash even if it is present based on some condition?

**Comment by apotonick** [comment]
@AnwarShah http://trailblazer.to/gems/reform/populator.html#skip

**Comment by pdfrod** [comment]
I have similar problem: I have a bunch of fields that I only want to validate if another field has a certain value. Using ActiveRecord validations I can easily solve it like this:
```
validates :field1, :field2, :field3, :field4, presence: { if: -> { another_field == 'certain value' } }
```

What's the recommended way to do this using dry-validations?

**Comment by apotonick** [comment]
Reform has its own API for that: http://trailblazer.to/gems/reform/validation.html#validation-groups

**Comment by fran-worley** [comment]
FWIW you can actually do this in dry validations using high level rules, custom predicates, validation block or a combination thereof.

They actually have an example for doing just that in their docs:

http://dry-rb.org/gems/dry-validation/high-level-rules/



Sent from my iPhone

On 22 Feb 2017, at 08:01, Nick Sutterer <notifications@github.com<mailto:notifications@github.com>> wrote:


Reform has its own API for that: http://trailblazer.to/gems/reform/validation.html#validation-groups

**Comment by pdfrod** [comment]
@apotonick I've just tried passing a proc to the `:if` option and it seems to work, however nothing in the docs mentions this kind of usage. From reading it, it feels like the `:if` option can only be used to specify the name of another validation group. Anyway, this solves my problem, thanks!

@fran-worley I actually tried High-level rules but for some reason it wasn't working, so I wasn't sure Reform supported them. But I've tried now on a new app and it works, so it must have been something I was doing wrong. Thanks for the help.

**Comment by fran-worley** [comment]
Glad you've got it sorted. 

Reform takes your validation blocks and converts them to a dry-validation schema so you should be able to use all aspects of dry-validation provided you're inside a validation block.

I'll mark this as solved, but get back to us or pop into the gitter room if you need anything else.
