### ISSUE TITLE
undefined method `Form' for Dry::Validation:Module 

### ISSUE THREAD

**Issue by efrendiaz** [trailblazer/reform#464]
Note: If you have a question about Reform, would like help using
Reform, want to request a feature, or do anything else other than
submit a bug report, please use the [Trailblazer gitter channel](https://gitter.im/trailblazer/chat).

Note: Rails/ ActiveRecord/ ActiveModel support.
As of Reform 2.2.0 all Rails/ Active-* code was moved to the [reform-rails](https://github.com/trailblazer/reform-rails) gem.
Make sure you are contributing to the correct gem!

### Complete Description of Issue

When you use reform dry on validations you get this error

` undefined method `Form' for Dry::Validation:Module `

I did some research and Form was renamed to Params in https://github.com/dry-rb/dry-validation/blob/1d0dcd30fd46a85654edda9389eb484f2eb2a0cc/CHANGELOG.md

### Steps to reproduce

Just try to use reform dry validation on a command with the latest trailblazer 

### Expected behavior

Don't get an error

### Actual behavior
getting this error ` undefined method `Form' for Dry::Validation:Module `

### System configuration
**Reform version**:
reform-2.2.4
### Full Backtrace of Exception (if any)

Failure/Error:
  validation do
    required(:email).filled
    required(:password).filled
  end

``` NoMethodError:
  undefined method `Form' for Dry::Validation:Module
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/reform-2.2.4/lib/reform/form/dry.rb:48:in `initialize'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/reform-2.2.4/lib/reform/form/dry.rb:33:in `new'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/reform-2.2.4/lib/reform/form/dry.rb:33:in `instance_exec'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/reform-2.2.4/lib/reform/validation.rb:15:in `validation'
# ./app/concepts/user/contract/create.rb:11:in `<class:Create>'
# ./app/concepts/user/contract/create.rb:5:in `<module:Contract>'
# ./app/concepts/user/contract/create.rb:4:in `<main>'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:374:in `block in require_or_load'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:352:in `require_or_load'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:330:in `depend_on'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:244:in `require_dependency'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:25:in `block in load_for'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `block in load_files'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `each'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `load_files'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:33:in `call'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:25:in `load_for'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:11:in `load_concepts'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:49:in `block (3 levels) in <module:Loader>'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `catch'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:199:in `block in halting'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `each'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/reloader.rb:89:in `prepare!'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:5:in `<main>'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# ./spec/rails_helper.rb:4:in `<main>'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# ./spec/models/device_spec.rb:1:in `<main>'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/efrendiaz/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'```

**Comment by AurimasLazdauskas** [comment]
Having the same issue.

**Comment by fran-worley** [comment]
The fix to allow newer versions of Dry-validation was released as part of disposable 0.4.4, but I see that Reform v2.2.2 is locked at 0.4.2. @apotonick is there any reason why we can't release a new version of the 2.2.x branch bumping the disposable dependency?

I've fixed this on 2.3.x branch but appreciate that with it still being an RC, it's not a viable option for all users.

**Comment by aiomaster** [comment]
I use the 2.3.x branch and it is working, but I still get the compatibility message:
`[dry-types] Form types were renamed to Params`

I think this is because we require "dry/validation/schema/form" instead of  "dry/validation/schema/params"  here:
https://github.com/trailblazer/reform/blob/c3afaff7868d49cd6d02578617c3215b724ae3a8/lib/reform/form/dry.rb#L2

**Comment by dr0verride** [comment]
As a work around, I added `require 'dry/validation/compat/form'` to my project and things started working. Doing this caused multiple warnings, but it fixed the reported issue and got my tests passing.

**Comment by Uysim** [comment]
I met the same problem but what @dr0verride did the job

**Comment by Uysim** [comment]
@dr0verride  I think your solution can not work on validation ```with: { form: true }``` user version ```2.3.0.rc1``` will help

**Comment by skcc321** [comment]
2.3.0.rc1 works very well. No problem at all.
the only thing which makes me angry is this damn warning.
"[dry-types] Form types were renamed to Params".
anybody, how to remove it at all?

**Comment by zbo09** [comment]
> As a work around, I added `require 'dry/validation/compat/form'` to my project and things started working. Doing this caused multiple warnings, but it fixed the reported issue and got my tests passing.

This sorted my problem!

**Comment by Bighamster** [comment]
+1

**Comment by emaglio** [comment]
@efrendiaz have you tried the 2.2.4 version?

**Comment by emaglio** [comment]
Just checked the change log of the 2.2.4v and the dependency with disposable is now >= 0.4.1 so I’m going to close this for now - we can reopen it if required
